### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#104]
Bounty: $1,000 for an accepted proposal + PR.

Consider: mailosaur or temp-email

Why:
- Common use case for e2e tests
- Allows us to use for core Helper.ai functionality

**Comment by m2rads** [comment]
Will tackle this next!

**Comment by adithyaakrishna** [comment]
hey! would love to work on this if this is open for public :)

**Comment by slavingia** [comment]
Feel free to discuss your approach and get feedback

**Comment by slavingia** [comment]
Signed up for https://mailosaur.com/ for email inbox testing for Flexile. Perhaps something we could use.

**Comment by m2rads** [comment]
Signed up for them and looks neat. I will try to ship this tonight in the open PR.

**Comment by m2rads** [comment]
Did you open an org account for Antiwork? Maybe I should use that.

**Comment by slavingia** [comment]
You can use your own for now and we can consolidate if it's a good fit

**Comment by slavingia** [comment]
Yep sounds good. I could imagine it being something shortest.com itself could provide at some point perhaps.

**Comment by m2rads** [comment]
Hi @slavingia! I added magic link support in Shortest. Updated the test case to login via magic link which will cover email validation as well. The demo is in PR: #183 

The only thing left to do is to add these two API keys from Mailosaur to Github action keys in this repo so that workflow will work: 

```typescript
MAILOSAUR_API_KEY
MAILOSAUR_SERVER_ID
```

Please also let me know the email address you create in the server so that I can use it in the test case. 

If there are anything else please let me know.

**Comment by slavingia** [comment]
added 
<img width="972" alt="image" src="https://github.com/user-attachments/assets/7e88cc84-fc5b-4f14-af63-bc57df829792" />
