### ISSUE TITLE
Get build green by fixing Clerk

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#170]

**Comment by m2rads** [comment]
So seems like for the preview env in Vercel we need to use the env vars for Clerk Dev. Right now we are using the production API keys for both preview and Prod env which is why we are getting the 400 error message when trying to sign in. 

Here's how to fix: 
In clerk make sure you are in Development env
Copy these two API keys that should start with `sk_test`: 

```typescript
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=sk_test
CLERK_SECRET_KEY=sk_tests
```

Navigate to Shortest project in Vercel and update these env vars. Make sure only preview env is update for this. 

![image](https://github.com/user-attachments/assets/d2929749-d766-4fbd-9319-266c83fb49fc)

I believe this should fix the issue we have with Clerk. Please let me know if you any help with this.

**Comment by slavingia** [comment]
Sweet. We should also update the README so that anti-work devs can pull the dev keys and not get any errors locally

**Comment by m2rads** [comment]
Updated the docs. Just an FYI I do not have permission to change Env vars in Vercel.

**Comment by slavingia** [comment]
Updated the keys.
