### ISSUE TITLE
Save state

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#52]
Why:

Should be able to leave the site and then come back, you don't lose your progress/tests being generated.

**Comment by crabest** [comment]
working on it

**Comment by crabest** [comment]
Since I can't store files data in the URL, I store them in local storage, while keeping the URL for the ids to use in the local storage.
the cons here of course it can be retrieved only from the browser, that's why I want to implement it in the database to keep the drafts of the tests before committing the changes....
Tell me what do you all think.

**Comment by crabest** [comment]
or just ship it?

**Comment by slavingia** [comment]
Good point. Should probably be done via local storage or even writing stuff to the db to store

**Comment by slavingia** [comment]
Like perhaps a jobs table that starts and then keeps track of new test files generated by the AI, and that is fed into the UI, instead of the UI being updated directly by the AI

I think we'll eventually move to background jobs completely with several auto-commits and then a merge upon green to further automate things so this would be inline with that!

**Comment by crabest** [comment]
Still working on it, what I am implementing to achieve this is creating users in the database when the user using github to authenticate to shortest, store pull requests info when the user starts generating tests for it, a new table where it will store each input and result of the AI to keep the logs of all the generated tests to be checked any time the user wants, also deleting it once the user commit the test.

What do you all think?

**Comment by slavingia** [comment]
@m2rads
